### ISSUE TITLE
Can't launch node microflo.js runtime on Arduino Uno

### ISSUE THREAD

**Issue by microspace** [microflo/microflo#133]
I get timeout error after trying to launch runtime
![image](https://user-images.githubusercontent.com/2958584/26927235-701de45c-4c6a-11e7-8628-b8bc1d3d4f24.png)
I've uploaded Standalon.ino into Arduino UNO, and connected it to PC

**Comment by jonnor** [comment]
Hi @microspace. Do you see the Standalone.ino sketch running on the Arduino? It should be blinking the quickly, around 3 times per second.

Also, can you try the updated instructions for Arduino found here: https://github.com/microflo/microflo-example-arduino ?

**Comment by jonnor** [comment]
I tested again on an Arduino Uno and I can reproduce the issue. It happens because the Uno restarts itself when connecting on serial. Working on a fix.

**Comment by jonnor** [comment]
Fixed in 0.4.1
