### ISSUE TITLE
Assign ids to component instances explicitly

### ISSUE THREAD

**Issue by pablochacin** [microflo/microflo#64]
In the current implementation, when the components instance are created (using the command 0xb), the id is assigned by the microflo runtime in the order they are created. However, this id is required to communicate with the component instances at runtime to establish the connection between components, and sent initialization messages. 

The following example may help clarify these ideas:

```
in(SerialIn) OUT -> IN fwd(Forward)
fwd() OUT -> IN out(SerialOut)

/* 
The microflo graph commands to instance above graph:
*/
const unsigned char graph[] PROGMEM = {
0x75,0x43,0x2f,0x46,0x6c,0x6f,0x30,0x31,
0xa,0x0,0x0,0x0,0x0,0x0,0x0,0x0,
0xf,0x1,0x0,0x0,0x0,0x0,0x0,0x0,
0xb,0x8,0x0,0x0,0x0,0x0,0x0,0x0,  /* create componet in id = 1 */
0xb,0x3,0x0,0x0,0x0,0x0,0x0,0x0,   /* create componet in fwd = 2 */
0xb,0x9,0x0,0x0,0x0,0x0,0x0,0x0,   /* create componet in out = 3 */
0xc,0x1,0x2,0x0,0x0,0x0,0x0,0x0,   /* create link  in -> fwd  */
0xc,0x2,0x3,0x0,0x0,0x0,0x0,0x0,  /* create link  fwd->out  */
0x14,0x0,0x0,0x0,0x0,0x0,0x0,0x0,
0xe,0x0,0x0,0x0,0x0,0x0,0x0,0x0
};
```

If for some reason the components are created in a different order, the ids will change, making that the initialization messages to be sent to the wrong component.

```
0xb,0x8,0x0,0x0,0x0,0x0,0x0,0x0,  /* create componet in id = 1 */
0xb,0x9,0x0,0x0,0x0,0x0,0x0,0x0,   /* create componet out id = 2 */
0xb,0x3,0x0,0x0,0x0,0x0,0x0,0x0,   /* create componet fwd id = 3 */
0xc,0x1,0x2,0x0,0x0,0x0,0x0,0x0,   /* create link  in -> out  <<< wrong */
```

This dependency on strict ordering of component creation makes the protocol frigile and only suitable for situations on which the graph commans come from the processing of an external representation of the graph (e.g. a json or fbp file), but not for other uses like dynamic graph creation and manipulation at run time.

It would be useful to be able to assign ids to components explicitly. In order to do so, I propose to change the component instantiation command to receive another parameter which specifies the component instance id. If this parameter is 0x00, then the runtime will assign one id. In this way, the proposed change will be backward compatible with existing behavior.

<pre>
0xb,0x8,<b>0x1</b>,0x0,0x0,0x0,0x0,0x0,  /* create componet in id = 1 */
0xb,0x9,<b>0x3</b>,0x0,0x0,0x0,0x0,0x0,   /* create componet out id = 3 */
0xb,0x3,<b>0x2</b>,0x0,0x0,0x0,0x0,0x0,   /* create componet fwd id = 2 */
0xc,0x1,0x2,0x0,0x0,0x0,0x0,0x0,   /* create link  in -> fwd  <<< works again! */
</pre>

**Comment by jonnor** [comment]
I think the real problems with dynamic graph manipulation is that we don't have a way to destroy just one of component and be able to reuse its nodeId afterwards. Because we assume that new nodes use consecutive numbers.
This could be solved with a free-list. In that case I think it is correct that the Network manages the nodeIds, and that the host does not explicitly specify an id. Instead the host should wait for the response to check which nodeId was assigned, and use that when setting up edges etc.

**Comment by jonnor** [comment]
We actually now support fully live programming since #104 was merged. The same behavior around node ids is still there, but I'm now even more convinced that respecting the runtime-assigned id is the way to go. See #105
