### ISSUE TITLE
microflo-runtime.html.map 404 in noflo-ui

### ISSUE THREAD

**Issue by forresto** [microflo/microflo#65]
`//# sourceMappingURL=microflo-runtime.html.map`

Can you remove this line from the bottom of build/emscripten/microflo-runtime.js?

**Comment by forresto** [comment]
Or commit the map... tired of

>  GET http://localhost:3000/browser/microflo-runtime.html.map 404 (Not Found)

**Comment by jonnor** [comment]
Should be fixed when moving things out to http://github.com/microflo/microflo-emscripten
Checked http://app.flowhub.io now and don't see any 404s for .map (or any at all actually)
