### ISSUE TITLE
Have soft/warning and hard/error on sending queue size

### ISSUE THREAD

**Issue by jonnor** [microflo/microflo#68]
To avoid sending buffer growing indefinetely (and not detecting this) we should monitor the queue length and give warnings/errors when too large.
On hard limit, the oldest packages should be dropped.

**Comment by bergie** [comment]
We might want to annotate edges as "optional" to mark what packets are safest to drop in these situations.

**Comment by jonnor** [comment]
Requests are now processed as fast as possible, based on responses from the microcontroller. Up to 100 messages can be pending, after which will throw Error
