### ISSUE TITLE
Get rid of component.io for browser build

### ISSUE THREAD

**Issue by jonnor** [microflo/microflo#84]
Should use webpack (or browserify), which uses NPM instead of an obsoleted, parallel universe packaging system.

Should allow us to get rid of the forks we have, like:
- https://github.com/microflo/buffer
- https://github.com/microflo/ieee754
- https://github.com/microflo/base64-js

**Comment by jonnor** [comment]
Have had some successes with webpack. One thing is that microflo is pulled into https://www.npmjs.com/package/fbp-protocol-client so that should also be fixed. And that is used by `fbp-spec` and `noflo-runtime`, which again is used by `noflo-ui`.

**Comment by jonnor** [comment]
@bergie do we use the component.io version of `fbp-protocol-client` anywhere now? If not then that unblocks this

**Comment by bergie** [comment]
@jonnor I don't think we do. Some 3rd parties might but in general component.io is anyway semi-broken by now

**Comment by jonnor** [comment]
Done since 0.3.54
