### ISSUE TITLE
Possible bug on master?

### ISSUE THREAD

**Issue by m-spiessens** [microflo/microflo#90]
storm@SIBYLLA:~/Development/microflo$ node microflo.js runtime -s /dev/ttyACM0 -b 115200
Using serial baudrate with /dev/ttyACM0 115200
Available serial ports:  [ '/dev/ttyACM0',
  '/dev/ttyS0',
  '/dev/ttyS1',
  '/dev/ttyS10',
  '/dev/ttyS11',
  '/dev/ttyS12',
  '/dev/ttyS13',
  '/dev/ttyS14',
  '/dev/ttyS15',
  '/dev/ttyS16',
  '/dev/ttyS17',
  '/dev/ttyS18',
  '/dev/ttyS19',
  '/dev/ttyS2',
  '/dev/ttyS20',
  '/dev/ttyS21',
  '/dev/ttyS22',
  '/dev/ttyS23',
  '/dev/ttyS24',
  '/dev/ttyS25',
  '/dev/ttyS26',
  '/dev/ttyS27',
  '/dev/ttyS28',
  '/dev/ttyS29',
  '/dev/ttyS3',
  '/dev/ttyS30',
  '/dev/ttyS31',
  '/dev/ttyS4',
  '/dev/ttyS5',
  '/dev/ttyS6',
  '/dev/ttyS7',
  '/dev/ttyS8',
  '/dev/ttyS9' ]
Using serial port: /dev/ttyACM0
MicroFlo runtime listening at 127.0.0.1:3569

/home/storm/Development/microflo/lib/runtime.coffee:653
        return callback(null, runtime);
               ^
TypeError: string is not a function
  at /home/storm/Development/microflo/lib/runtime.coffee:488:20
  at Server.<anonymous> (/home/storm/Development/microflo/lib/runtime.coffee:479:16)
  at Server.g (events.js:180:16)
  at Server.emit (events.js:92:17)
  at net.js:1056:10
  at process._tickCallback (node.js:458:13)

---

storm@SIBYLLA:~/Development/microflo$ uname -a
Linux SIBYLLA 3.19.0-59-generic #66~14.04.1-Ubuntu SMP Fri May 13 17:27:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
storm@SIBYLLA:~/Development/microflo$ npm -v
3.9.5
storm@SIBYLLA:~/Development/microflo$ node -v
v0.10.45

---

[npm_list.txt](https://github.com/microflo/microflo/files/309531/npm_list.txt)

**Comment by jonnor** [comment]
Hi @m-spiessens thanks for reporting. This was indeed a bug, should be fixed in master now: https://github.com/microflo/microflo/commit/667036e59f13651c43549d8f1bf53245a8fb7ed0
